### ISSUE TITLE
Rendre les % de perf exploitables pour les dévs

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-france#1005]
![](https://github.trello.services/images/mini-trello-icon.png) [Make performance variations actionable for developers](https://trello.com/c/A3GQ1HMS/30-ensure-developers-know-when-frances-performance-improves-decreases)

**Pour** les dévs

**Story :**

Quand je contribue à OpenFisca,
J'ai besoin d'avoir un retour rapide sur la performance,
Pour pouvoir changer l'approche de mon code actuel et en choisir une autre.

**Definition of done :**

Version courte : l'effort **minimal** pour pouvoir implémenter #926 

Version longue : avoir un indicateur qui montre si des changements améliorent ou empirent la performance du test suite, qui soit facilement compréhensible et découvrable pour les dévs. 

**Issues :**

- [x] Calculer la performance par test #1001 
- [x] Indicateur de performance par test #1002 
- [ ] Ajouter test de performance sur CircleCI ou autre #1004
- [ ] Présenter indicateur de perf de façon compréhensible #1003 
- [ ] Refactoriser les scripts suite aux retours de la communauté
- [ ] Compléter la documentation

**Liens utiles :**

- https://stackoverflow.com/questions/3045556/how-to-profile-my-code

**Comment by maukoquiroga** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ensure developers know when France's performance improves/decreases](https://trello.com/c/A3GQ1HMS/30-ensure-developers-know-when-frances-performance-improves-decreases)

**Comment by magopian** [comment]
Would it make sense to use something that already exists, is automated, and is provided by CircleCI, like the [CircleCI insights](https://circleci.com/blog/announcing-circleci-insights-helping-you-understand-your-builds/)?

----

Est-ce qu'il serait pertinent d'utiliser quelque chose qui existe déjà, est automatique, et fourni par CirclCI comme [CircleCI insights](https://circleci.com/blog/announcing-circleci-insights-helping-you-understand-your-builds/)?

**Comment by maukoquiroga** [comment]
Hello @magopian, à mon avis il y a deux jobs-to-be-done :

1. savoir si nos travaux améliorent ou empirent la performance d'OpenFisca (France) ; et, finalement,
2. pouvoir plus simplement faire du TDD, difficile aujourd'hui.

CircleCI Insights est à mon avis un _second-best_ : en première instance nous avons essayé d'isoler le temps d'execution des tests du reste des tâches du job run, comme le sont le provisioning, l'installation de dependences, etc.

Cela c'est avéré assez compliqué, et je crois que CircleCI Insights peut être une bonne alternative pour résoudre 1.

Que pensez-vous @sandcha @fpagnoux @Anna-Livia ?

**Comment by guillett** [comment]
Pour ajouter du contexte pour 2. J'ai, effectivement, eu de grandes difficultés à faire du TDD sur OpenFisca-France. Ayant changé de machine récemment, ce n'est plus un problème aussi important qu'il y a quelques mois.

**Comment by Morendil** [comment]
Je ferme suite aux discussions sur #926 et IRL.
