### ISSUE TITLE
Roadmap OF MSA jusqu'à février 2019

### ISSUE THREAD

**Issue by JenniferTelep** [openfisca/openfisca-france#1130]
Bonjour @guillett 

Cette issue présente les prochains développements prévus par l'équipe OF MSA jusqu'à février 2019.
NB: le macro-planning de soumission de PR sera communiqué asap sur cette issue.

**Réformes des aides au logement**
- [ ] [AL 2019] Réforme du calcul des droits aux aides au logement à partir d'avril 2019 tenant compte des ressources contemporaines (#1118)
- [x] Revalorisation des barèmes spécifiques à certains publics "logements foyers" - Aides au logement (#1199)
- [x] Application d'un barème spécifique à certains publics "accession" - Aides au logement
- [x] Analyse à mener sur la notion de locataire_hlm vs. la notion de logement conventionné (#1214) 

**Travaux de fiabilisation d'OpenFisca**
- [x] Intégration du calcul de la rente d'accident du travail (#1122)
- [x] Fiabilisation de l'historique des paramètres d'aide au logement (intégration des valeurs manquantes) 
- [x] Fiabiliser historiquement les paramètres AL dans les DOM (#1106)
- [x] Prise en compte de la contribution à la réduction de la dette sociale (CRDS) dans le calcul des allocations familiales (#1044)
- [x] Fiabilisation des paramètres OpenFisca pour la prime d'activité 
- [ ] Fiabilisation des paramètres OpenFisca pour l'allocation de solidarité spécifique (#1048)
- [ ] Application d'un montant minimal de l'AAH en cas d'hospitalisation/incarceration (#999)

**Aides Famille/Solidarité**

Revalorisation des prestations familiales au 1er avril 2018
- [x] ASF (#1119)
- [x] AF (#1120)
- [x] CF (#1121)
- [x] Simplification du mode de calcul du plafond de ressources pour les bénéficiaires de l'AAH (#1185)

Intégration des paramètres pour les DOM
- [x] RSA (#1125)
- [ ] ASS (#1126)
- [x] PPA (#1127)
- [x] AF (#1128)
- [ ] CMU-ACS (#1129)

Revalorisations de janvier 2019 : 
- [x] AL (#1237)
- [x] AF (#1238)
- [x] CF (#1239)
- [x] PAJE (#1240)

Autres
- [ ] Calcul de la PPA: rétablissement de la dérogation pour la prise en compte de la pension d'invalidité et la rente AT-MP (#1124)
- [ ] Simplification du mode de calcul du plafond de ressources pour les bénéficiaires de l'allocation adulte handicapé (AAH) (#1185)

Pour info : @Lashchuk , @ThibaultCCMSA , @SChiusa , @JenniferTelep , @LacombeEric, @frtomas , @mtifarine , @marchand-laetitia-msa, @jmdallais

**Comment by benjello** [comment]
@JenniferTelep : est-ce que les paramètres des différents points mentionnés ci-dessus (montant de revalorisation etc) sont connus de la MSA à l'heure ou j'écris ce message ?
Merci !

**Comment by ThibaultCCMSA** [comment]
@benjello : Nos travaux sont encore en cours de validation et de consolidation avec nos experts métier. On vous tient informés.

**Comment by benjello** [comment]
Merci !

**Comment by Morendil** [comment]
Bonjour @JenniferTelep je me suis permis d'intervenir sur le formatage du descriptif de cette issue, pour faciliter le suivi, en faisant le lien avec les issues déjà ouvertes avec le label `contrib:msa`.

**Comment by Morendil** [comment]
@JenniferTelep @ThibaultCCMSA Je n'ai pas eu de réponse à la question que je posais [ici](https://github.com/openfisca/openfisca-france/pull/1248#discussion_r247979407), comme c'est réversible je vais me permettre de fermer les issues concernées. N'hésitez pas à me faire signe pour discuter du process.

**Comment by JenniferTelep** [comment]
> @JenniferTelep @ThibaultCCMSA Je n'ai pas eu de réponse à la question que je posais [ici](https://github.com/openfisca/openfisca-france/pull/1248#discussion_r247979407), comme c'est réversible je vais me permettre de fermer les issues concernées. N'hésitez pas à me faire signe pour discuter du process.

@Morendil, désolée pour la réponse tardive, on avait bien vu le message et on est OK sur une issue roadmap globale +ouverture des issues détaillées seulement au début des travaux.

**Comment by MehdiBenHnin** [comment]
@guillett , Bonjour je suis Mehdi Ben Hnin je suis la nouvelle ressource de l'équipe MSA/OF, en remplacement de Jennifer Telep. J'ai créé mon compte GitHub à l'instant, y a-t-il des démarches supplémentaires à effectuer pour participer à la communauté OF ? 

Pour info : @JenniferTelep @ThibaultCCMSA @jmdallais

**Comment by Morendil** [comment]
Bonjour @MehdiBenHnin et ravi de faire virtuellement ta connaissance! Pas de démarches particulières, et il y a certainement beaucoup de choses qu'il serait utile de savoir sur la nature et le fonctionnement d'OpenFisca. Certaines sont décrites dans nos diverses documentations mais sans doute pas tout. Serais-tu intéressé pour qu'on en discute cette semaine ? Mon mail est dans mon profil Github et je suis en mesure de prendre 1h par téléphone, t'accueillir dans les locaux de la DINSIC ou me déplacer à la DSS.

Cc @sandcha @maukoquiroga @renardpal @antoningarrone @fpagnoux

**Comment by MehdiBenHnin** [comment]
Bonjour  @sandcha @maukoquiroga @Morendil 

J'ai ajouté la roadmap OF MSA jusqu'à Juin 2019 ici  #1316 

@ThibaultCCMSA @mtifarine @frtomas
