### ISSUE TITLE
Roadmap OF MSA jusqu'à Octobre 2019

### ISSUE THREAD

**Issue by MehdiBenHnin** [openfisca/openfisca-france#1352]
Bonjour @Morendil  @sandcha  @maukoquiroga 

Cette issue présente les développements prévus par l'équipe OF MSA pour la version 5.1. 

Date de validation souhaitée : **25/09** 

A valider - [ Date de validation souhaité 25/09/2019 ] 

- [x] Priorité 1 : Réforme de fusion de l’ACS et de la CMU-c au 1er Novembre 2019 

- [x] Priorité 2 : Revalorisation de certains paramètres de calcul des AL au 1er Octobre 2019 

Déjà validé 

- [x] [ Fiabilisation ] Revalorisation des Forfaits logements représentatifs des avantages en nature pour les propriétaires ou occupants à titre gratuit et les bénéficiaires d'une aide personnelle au logement au 1er Avril 2019.

- [x] Réforme de fusion des compléments à l’AAH ( Fusion du CR et de la MVA au profit de la MVA ) au 1er Décembre 2019

@ThibaultCCMSA   @mtifarine @frtomas @maukoquiroga  @guillett

**Comment by maukoquiroga** [comment]
Bonjour @MehdiBenHnin, merci. Comme discuté, pour les réformes, le plus en amont nos équipes peuvent travailler ensemble, le plus simple sera l'intégration des changements.

Cela peut prendre la forme d'une session de mob ou pair programming au tout début de l'implémentation, c'est-à-dire au moment d'écrire la première ligne de code.

cc @sandcha @Morendil

**Comment by maukoquiroga** [comment]
@MehdiBenHnin Si tout est bon de votre côté, peut-on fermer cet issue ?

**Comment by MehdiBenHnin** [comment]
> @MehdiBenHnin Si tout est bon de votre côté, peut-on fermer cet issue ?

@maukoquiroga Dans la mesure ou les deux PR ouvertes ont été mergées, absolument on peut fermer l'issue. 

@ThibaultCCMSA @frtomas @mtifarine

**Comment by guillett** [comment]
Juste un point d'attention selon moi. Les dernières version d'OpenFisca nécessaire Python 3.7
Je ne sais pas ce qui est dans le PNDS aujourd'hui mais côté MA on est sur du 3.6.
