### ISSUE TITLE
Roadmap OF pour la fin 2019 

### ISSUE THREAD

**Issue by MehdiBenHnin** [openfisca/openfisca-france#1373]
@Morendil @sandcha @maukoquiroga @guillett 

Cette issue présente les développements prévus par l'équipe OF MSA pour la version 6.0

**Fiabilisations prévues** 

- [ ] Priorité 1 - Fiabilisation de la prise en compte des frais déductibles dans OpenFisca pour les revenus assimilés rentes ( Retraite )
- [ ] Priorité 2 - Fiabilisation des paramètres OpenFisca pour l'ASS – Abattement sur les revenus de substitution pour les couples pacsés dont l’un des conjoints est micro-entrepreneur
- [ ] Priorité 3 - Contrôle des barèmes et montant spécifiques aux DOM - TOM pour les AL

 **Contrôles** ( Les contrôles de ces aides ne déclencheront des fiabilisations et des PR que si une anomalie est détectée ) 
•	Allocations Familiales 
•	Allocation de base de la PAJE
•	Allocation adules handicapés
•	Allocation de soutien familial

**Comment by sandcha** [comment]
Bonjour @MehdiBenHnin, Avez-vous du nouveau concernant la liste envisagée ci-dessus ? 🙂 
@maukoquiroga et moi sommes disponibles pour échanger sur les priorités de cette toute fin d'année et de T1 2020. Qu'en dites-vous ? Seriez-vous disponible pour un appel demain ou en début de semaine prochaine ?

**Comment by MehdiBenHnin** [comment]
Bonjour @sandcha @maukoquiroga  @ThibaultCCMSA 

Je vais en discuter avec Thibault et vous fait un retour dès que possible.

**Comment by tomy-isabelle** [comment]
PNDS - raodmap obsolète - clôturée ce jour
