### ISSUE TITLE
Roadmap OF pour Janvier - Avril 2020

### ISSUE THREAD

**Issue by MehdiBenHnin** [openfisca/openfisca-france#1404]
@Morendil @sandcha @maukoquiroga @guillett @frtomas @mtifarine

Cette issue présente les développements prévus par l'équipe OF MSA pour la version 7.0 d'avril du PNDS.

**Fiabilisations :**

- [x] Fiabilisation de l'abattement spécifique aux assistants maternels (asmat) et aux journalistes  
- [x] Fiabilisation de l'abattement fiscal pour les personnes invalides et agées (+de 65ans) [**Prestations Familiales**] 
- [x] Fiabilisation du calcul du RSA pour les apprentis
- [ ] Fiabilisation des paramètres OpenFisca pour l'ASS [ Situation spécifique aux couples pacsés dont l'un des conjoints est un micro entrepreneur ] 

**Revalorisations :** 

- [x] Revalorisation des Allocations Familiales (AF) en avril 2020
- [x] Revalorisation du Complément Familial (CF)  en avril 2020
- [x] Revalorisation de l'Allocation de Soutien Familial (ASF) en avril 2020 
- [x] Revalorisation de l'allocation de base (PAJE) en avril 2020
- [x] Revalorisation de l'Allocation Supplémentaire d'Invalidité (ASI) en avril 2020
- [ ] Revalorisation de l'Allocation Supplémentaire de Solidarité (ASS) en avril 2020

**Comment by sandcha** [comment]
Vu avec équipe mesdroitssociaux : tous les éléments ont été réalisés sur la branche `msa_fork_al_css_v1_7_1` sauf pour l'ASS (fiabilisation et revalorisation à venir).

**Comment by sandcha** [comment]
AL : revalorisation d'octobre en cours sur `msa_fork_al_css_v1_7_1` (en qualification ; déploiement à venir)
Taux 2020 du LEP (Livret d'Epargne Populaire) présent sur `msa_fork_al_css_v1_7_1`

**Comment by sandcha** [comment]
Comme convenu, des PR ont été ouvertes ces dernières semaines par sujet sur la base de la branche `msa_fork_al_css_v1_7_1` (qui ne comprend pas d'ASS tel qu'indiqué plus haut) : 

**Fiabilisations :**

- [x] Fiabilisation de l'abattement spécifique aux assistants maternels (asmat) et aux journalistes  [concerne les aides au logement (_AL_)] > #1451 a été créée mais étant conséquente, il a été proposé de valider les paramètres en premier via la PR #1460.
- [x] Fiabilisation de l'abattement fiscal pour les personnes invalides et agées (+de 65ans) [**Prestations Familiales**] > ⚠️ Modification non identifiée sur `msa_fork_al_css_v1_7_1` ; incertitude sur le paramètre concerné (décrit comme fiscal mais prestations familiales 🤔) 
- [x] Fiabilisation du calcul du RSA pour les apprentis > #1453 (RSA + apprenti) et #1454 (PPA + apprenti) intégrées.


**Revalorisations :** 

- [x] Revalorisation des Allocations Familiales (AF) en avril 2020 > #1452 intégrée.
- [x] Revalorisation du Complément Familial (CF)  en avril 2020 > #1452 intégrée.
- [x] Revalorisation de l'Allocation de Soutien Familial (ASF) en avril 2020 > ⚠️ Modification non identifiée sur `msa_fork_al_css_v1_7_1` ; sur la [branche master actuelle](https://github.com/openfisca/openfisca-france/tree/132fb671a6a0fa104e832983986bc47533306037/openfisca_france/parameters/prestations/prestations_familiales/asf), les dernières revalorisations d'ASF datent de 2018.
- [x] Revalorisation de l'allocation de base (PAJE) en avril 2020 > ⚠️ Modification non identifiée sur `msa_fork_al_css_v1_7_1` ; sur la [branche master actuelle](https://github.com/openfisca/openfisca-france/tree/132fb671a6a0fa104e832983986bc47533306037/openfisca_france/parameters/prestations/prestations_familiales/paje), les dernières revalorisations de PAJE datent au mieux de 2018.
- [x] Revalorisation de l'Allocation Supplémentaire d'Invalidité (ASI) en avril 2020 > #1459 (paramètres) et #1455 (ensemble + AAH)

Par ailleurs : 
* Les revalorisations de réduction de loyer de solidarité (RLS) ont été intégrées par la #1456.
* Un delta de commits a été présenté en #1457 mais clôturé.

**Comment by tomy-isabelle** [comment]
PNDS - roadmap à clôturer. cf roadmap à suivre de Octobre 2021.
