### ISSUE TITLE
Emplacement et valeurs des meta données dans les paramètres du modèle

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-france#1534]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

J'ai voulu préciser l'unité d'un paramètre pour la PR #1501 (cf. [cette discussion](https://github.com/openfisca/openfisca-france/pull/1501#discussion_r629769623)). L'unité représentative du paramètre était le mois : `unit: month`.

### À quoi m'attendais-je ?

À trouver cette unité dans la liste d'unités de la [documentation](https://openfisca.org/doc/coding-the-legislation/legislation_parameters.html#how-to-write-a-new-parameter).

### Que s'est-il passé en réalité ?

J'ai trouvé ceci dans la [documentation des paramètres](https://openfisca.org/doc/coding-the-legislation/legislation_parameters.html#how-to-write-a-new-parameter) : 
```
Possible attributes are:

- description (optional) Description;
- metadata (optional) Can be:
  - reference (optional) Legislative reference;
  - unit (optional) Can be:
    - year: The values are years;
    - currency: The values are in the unit of currency of the country;
    - /1: The values are percentages, with 1.0=100%;
- values: Value of the parameter for several dates.
```

Où `month` ne figure pas.
Et où l'unité est sous `metadata`.

Or, `openfisca-france` utilise maintenant `month` et fait cohabiter cela avec l'ancienne syntaxe des paramètres où unité et référence ne sont pas sous `metadata`. 🙃 

**Mais alors, quelle est notre référence ? Ce n'est pas très clair.**

* Aujourd'hui, par la documentation et `openfisca-core` (via, par exemple, [ce commentaire à jour](https://github.com/openfisca/openfisca-core/blob/725322001e17b82c5a6840f5620a30add052d0bf/openfisca_core/parameters/parameter_at_instant.py#L14)), nous laissons entendre que la syntaxe de référence place `unit` et `reference` sous `metadata`. 
  * Sur `openfisca-france` on conserve majoritairement l'ancienne syntaxe mais la question pourrait ressurgir sous peu par le rapprochement avec les barèmes IPP qui emploient `metadata`.
* Et la valeur `month` n'est jamais présentée.
  * On pourrait l'ajouter à la documentation mais alors, la règle pour l'ajout d'une telle proposition est encore plus floue que pour l'ajout d'une feature parce que, de mémoire, ce n'est pas quelque chose de contraint par `openfisca-core` qui a priori ne nous contraint que sur les clefs des paramètres (on est a priori libre de mettre les valeurs de notre choix). 
  * De même la [spécification de l'API Web](https://github.com/openfisca/openfisca-core/blob/725322001e17b82c5a6840f5620a30add052d0bf/openfisca_web_api/openAPI.yml#L207-L232) ne nous donne pas plus d'information ou de contrainte.

Ainsi, ce petit ajout d'unité rencontre la cohabitation implicite de deux syntaxes des paramètres et en raison des travaux en cours sur #1519, il me semble que le sujet des `metadata`  dans `openfisca-france` se pose de nouveau. 

Selon vous, migrons-nous petit à petit vers la syntaxe où `unit` et `reference` sont sous `metadata` ?
Et proposons-nous la valeur `month` de `unit` dans la documentation partagée par les pays afin qu'elle soit découvrable ?
Ou aborderiez-vous la question autrement ? 🙂 

### Contexte

Je m'identifie plus en tant que :

- [ ] Contributeur·e : je contribue à OpenFisca France.
- [ ] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [ ] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.
