### ISSUE TITLE
Harmonisation IPP [2/10] -  Impôts sur le Revenu:

### ISSUE THREAD

**Issue by Sasha-Laniece** [openfisca/openfisca-france#1598]
Hello hello !

Suite au travail d'harmonisation des paramètres IPP et OpenFisca ( enclanché ici: https://github.com/openfisca/openfisca-france/issues/1519 ), je liste tous les sous-dossiers **de la section Impôts sur le Revenu** des Barèmes IPP qu'il reste à harmoniser.

La liste complète est ici: https://www.ipp.eu/baremes-ipp/impot-sur-le-revenu/

L'objectif est que chacun puisse s'emparer d'un dossier, le notifier ici, faire le travail d'harmonisation (en suivant la méthode telle que décrite ici: https://cloud.leximpact.dev/index.php/s/2Wg28jsDiZQqj7Q ) et mettre les PR associées et éventuellement les issues.
NB: N'hésitez pas à découper les dossiers en sous-dossiers si besoin !

Initialisation: https://github.com/openfisca/openfisca-france/issues/1823
Amélioration: https://github.com/openfisca/openfisca-france/issues/1876

Voici les dossiers en cours de traitement / à traiter: 

1 - Barème de l'impôt sur le revenu (depuis 1945)
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours [Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1917]
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

2 - Anciens barèmes de l'impôt général sur le revenu
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours
   -  PR en cours : https://github.com/openfisca/openfisca-france/pull/1822
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

3 - Calcul des revenus imposables
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1952 et https://github.com/openfisca/openfisca-france/issues/1955 et https://github.com/openfisca/openfisca-france/issues/1958 et https://github.com/openfisca/openfisca-france/issues/1960 et https://github.com/openfisca/openfisca-france/issues/1968 )
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

4 - Calcul de l'impôt sur le revenu
- [x] En cours d'harmonisation (Branche: harmonisation_calcul_impot_revenu)
- [x] PR harmonisation en cours :  
   -  Plafond QF 1 : https://github.com/openfisca/openfisca-france/pull/1931
   - Plafond QF 2 : https://github.com/openfisca/openfisca-france/pull/1933
   -  Plus Values 1  : (Lien vers la PR: https://github.com/openfisca/openfisca-france/pull/1557 ) 
   -  Plus Values 2  : https://github.com/openfisca/openfisca-france/pull/1933
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

5 - Calcul des réductions d'impôts
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1935 et https://github.com/openfisca/openfisca-france/issues/1941 et https://github.com/openfisca/openfisca-france/issues/1944)
- [ ] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

6 - Calcul des crédits d'impôts
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours :
   -  PR en cours : https://github.com/openfisca/openfisca-france/pull/1920
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

7 - Contributions exceptionnelles
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1962 )
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

**Comment by Sasha-Laniece** [comment]
Harmonisation du dossier terminée !
