### ISSUE TITLE
Harmonisation IPP [3/10] - Taxation du capital

### ISSUE THREAD

**Issue by Sasha-Laniece** [openfisca/openfisca-france#1599]
Hello hello !

Suite au travail d'harmonisation des paramètres IPP et OpenFisca ( enclanché ici: https://github.com/openfisca/openfisca-france/issues/1519 ), je liste tous les sous-dossiers **de la section Taxation du capital** des Barèmes IPP qu'il reste à harmoniser.

La liste complète est ici: https://www.ipp.eu/baremes-ipp/taxation-du-capital/

L'objectif est que chacun puisse s'emparer d'un dossier, le notifier ici, faire le travail d'harmonisation (en suivant la méthode telle que décrite ici: https://cloud.leximpact.dev/index.php/s/2Wg28jsDiZQqj7Q ) et mettre les PR associées et éventuellement les issues.
NB: N'hésitez pas à découper les dossiers en sous-dossiers si besoin !

Initialisation: https://github.com/openfisca/openfisca-france/issues/1818
Tests: https://github.com/openfisca/openfisca-france/issues/1834
Voici les dossiers en cours de traitement / à traiter: 

1 - Prélèvement forfaitaire sur les revenus du capital
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1804 et https://github.com/openfisca/openfisca-france/issues/1824 )
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

2 - Prélèvements sociaux
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [ ] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1803 )
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

3 - Impôt sur les grandes fortunes (IGF) - (1982-1986)
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1815)
- [ ] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

4 - Impôt de solidarité sur la fortune (ISF) - (1989 - 2017)
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1816)
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

5 - Impôt sur la fortune immobilière (IFI) - à partir de 2018
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1817 )
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

**Comment by Sasha-Laniece** [comment]
Harmonisation du dossier terminée !
