### ISSUE TITLE
Harmonisation IPP [6/10] - Prestations Sociales

### ISSUE THREAD

**Issue by Sasha-Laniece** [openfisca/openfisca-france#1600]
Hello hello !

Suite au travail d'harmonisation des paramètres IPP et OpenFisca ( enclanché ici: https://github.com/openfisca/openfisca-france/issues/1519 ), je liste tous les sous-dossiers **de la section  Prestations Sociales** des Barèmes IPP qu'il reste à harmoniser.

La liste complète est ici: https://www.ipp.eu/baremes-ipp/prestations-sociales/

L'objectif est que chacun puisse s'emparer d'un dossier, le notifier ici, faire le travail d'harmonisation (en suivant la méthode telle que décrite ici: https://cloud.leximpact.dev/index.php/s/2Wg28jsDiZQqj7Q ) et mettre les PR associées et éventuellement les issues.
NB: N'hésitez pas à découper les dossiers en sous-dossiers si besoin !

Initialisation:  https://github.com/openfisca/openfisca-france/issues/1747 et https://github.com/openfisca/openfisca-france/issues/1753
Et aussi: https://github.com/openfisca/openfisca-france/issues/1668

Voici les dossiers en cours de traitement / à traiter: 

1 - Prestations familiales
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1749, https://github.com/openfisca/openfisca-france/issues/1789, https://github.com/openfisca/openfisca-france/issues/1790, https://github.com/openfisca/openfisca-france/issues/1796, https://github.com/openfisca/openfisca-france/issues/1800)
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

2 - Allocations logement
- [x] En cours d'harmonisation (Branche: harmonisation_)
- [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1751 et https://github.com/openfisca/openfisca-france/issues/1772 et https://github.com/openfisca/openfisca-france/issues/1777 )
- [x] Harmonisation merged !
- [ ] Formules en cours de vérification (Branche: check_ )
- [ ] PR check en cours (Lien vers la PR: )
- [ ] Check merged !

3 - Prestations liées à l'état de santé
  3.1 - Invalidité
  - [x] En cours d'harmonisation (Branche: harmonisation_)
  - [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1766 et https://github.com/openfisca/openfisca-france/issues/1767 )
  - [x] Harmonisation merged !
  - [ ] Formules en cours de vérification (Branche: check_ )
  - [ ] PR check en cours (Lien vers la PR: )
  - [ ] Check merged !
  
  3.2 - Perte d'autonomie des personnes âgées
  - [x] En cours d'harmonisation (Branche: harmonisation_)
  - [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1769 )
  - [x] Harmonisation merged !
  - [ ] Formules en cours de vérification (Branche: check_ )
  - [ ] PR check en cours (Lien vers la PR: )
  - [ ] Check merged !

4 - Solidarité et insertion
  4.1 - Minima sociaux
  - [x] En cours d'harmonisation (Branche: harmonisation_)
  - [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1750 et https://github.com/openfisca/openfisca-france/issues/1782 et https://github.com/openfisca/openfisca-france/issues/1784)
  - [x] Harmonisation merged !
  - [ ] Formules en cours de vérification (Branche: check_ )
  - [ ] PR check en cours (Lien vers la PR: )
  - [ ] Check merged !
  
  4.2 - Minimum vieillesse et droits non-contributifs de retraite
  - [x] En cours d'harmonisation (Branche: harmonisation_)
  - [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1781)
  - [x] Harmonisation merged !
  - [ ] Formules en cours de vérification (Branche: check_ )
  - [ ] PR check en cours (Lien vers la PR: )
  - [ ] Check merged !

  4.3 - Autre solidarité
  - [x] En cours d'harmonisation (Branche: harmonisation_)
  - [x] PR harmonisation en cours (Lien vers la PR: https://github.com/openfisca/openfisca-france/issues/1752 et https://github.com/openfisca/openfisca-france/issues/1780)
  - [x] Harmonisation merged !
  - [ ] Formules en cours de vérification (Branche: check_ )
  - [ ] PR check en cours (Lien vers la PR: )
  - [ ] Check merged !

**Comment by Sasha-Laniece** [comment]
Pour info le script de modification des cotsoc est mergé, et ça se passe ici:
https://github.com/openfisca/openfisca-france/pull/1553

**Comment by Sasha-Laniece** [comment]
Harmonisation du dossier terminée !
