### ISSUE TITLE
[EPIC][PLFSS Annexe 5] Taux de couverture exonérations de cotisations et contributions

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-france#1925]
Hello,

Pour une opportunité d'évaluation continue des dispositifs d'exonération de cotisations et contributions citées en [Annexe 5 du PLFSS 2022 = PRÉSENTATION DES MESURES D’EXONÉRATIONS DE COTISATIONS ET CONTRIBUTIONS ET DE LEUR COMPENSATION](https://www.securite-sociale.fr/files/live/sites/SSFR/files/medias/PLFSS/2022/PLFSS-2022-Annexe%205.pdf), divers membres de la communauté doivent déterminer la couverture du sujet par openfisca-france mais cela n'est pas documenté.

Il s'agit donc, pour chaque dispositif de l'Annexe 5 au PLFSS 2022 : 

- [ ] de déterminer s'il est modélisé
- [ ] quel est le % de modélisation pour la couverture totale du sujet
- [ ] pour une estimation budgétaire, quelles seraient les bases de données dont il faudrait disposer

À terme, il s'agirait d'utiliser openfisca-france pour la modélisation des éléments manquants et l'évaluation en continu de ces dispositifs tant d'un point de vue cas types que d'un point de vue budgétaire.

Les dispositifs de l'Annexe 5 sont répartis sur quelques issues thématiques que voici : 
[en cours]

### Contexte

Je m'identifie plus en tant que :

- [x] Contributeur·e : je contribue à OpenFisca France.
- [ ] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [x] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.
