### ISSUE TITLE
Implementer les reformes du GT de lutte contre le non recours

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-france#888]
L’objectif est de simuler des scénarios de réformes du calcul des prestations sociales qui simplifient le parcours des utilisateurs dans leur accès au droit (simplifier le parcours de la demande et la compréhension de leurs droits).

### Cas types

- Suppression De La Taxe D’habitation Pour 80 % Des Foyers
- Suppression Ou Baisse De Cotisations Sociales Sur Les Revenus Du Travail
- Augmentation De La Prime D’activité
- Revalorisation Du Complément Mode De Garde
- Augmentation Du Minimum Vieillesse
- Crédit D’impôts Sur Les Services À La Personne Pour Tous Les Français
- Revalorisation De L’allocation Adultes Handicapés
- Aides À La Transition Écologique

### Cas de test

- [x] Calcul des allocations logement sur les 12 derniers mois des revenus fiscaux (mêmes natures de ressources qu’actuellement mais sur une période d’un an). Ceci avec neutralisation des abattements chômage/retraite/aah/invalidité/ald (affection longue durée). openfisca/tutorial#14
- [ ] ~~Application de la base ressource décrite ci-dessus (cas 1) aux allocations familiales.~~
- [ ] ~~Calcul des allocations logement sur les 3 derniers mois des revenus fiscaux (mêmes natures de ressources qu’actuellement mais sur une période de trois mois). Ceci avec neutralisation des abattements chômage/retraite/aah/invalidité/ald (affection longue durée).~~
- [ ] ~~Application de la base ressource décrite ci-dessus (cas 3) aux allocations familiales.~~
- [ ] ~Calcul de l’aah annuelle sur les 12 derniers mois des revenus fiscaux (mêmes natures de ressources qu’actuellement mais sur une période de 12 mois au lieu de n-2).~
- [ ] ~~Calcul des RSA/PPA sur le net fiscal (non sur le net perçu).~~

### Tâches support

- [x] Script pour transformer de cas MesAides en OpenFisca openfisca/tutorial#7
- [x] Participation à l'écriture d'un article  de blog openfisca/tutorial#25
- [ ] ~~Voir si l'on peut ouvrir ces situations type et les publier sur data.gouv.fr~~

**Comment by guillett** [comment]
À rapprocher de https://github.com/openfisca/openfisca-france/pull/881 pour les « Cas types ».
